# Build stage
FROM golang:1.24 AS builder
WORKDIR /app

# Copy go mod/sum and download
COPY go.mod go.sum ./
RUN go mod download

# Copy source code over and build
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o process_kills ./cmd/process_kills.go
RUN chmod +x /app/process_kills

# Final stage
FROM scratch
COPY --from=builder /app/process_kills /app/process_kills
ENTRYPOINT ["app/process_kills"]